version: 'latest'

services:
  nodejs:
    image: phongvanngo/nova-file-service
    container_name: nova-file-service-uat
    env_file:
      - .env
    environment:
      - DOMAIN=$DOMAIN
      - PORT=$PORT
    ports:
      - "$DOCKER_PORT:$PORT"
    volumes:
      - $VOLUME_DATA_PATH:/uploads
