version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "$MYSQL_DOCKER_PORT:3306"
    volumes:
      - $VOLUME_DATA_PATH:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "$ADMINER_DOCKER_PORT:8080"
volumes:
  db_data:
