version: "3.8"
services:
  backend:
    image: phongvanngo/medusajs-backend
    container_name: matkinh53-test-v1
    env_file:
      - .env
    environment:
      DATABASE_URL: $DATABASE_URL
      REDIS_URL: redis://45.119.85.106:3700
      DATABASE_TYPE: postgres
      JWT_SECRET: kaka
      COOKIE_SECRET: kaka
      PORT: 9000
      NODE_ENV: production
    ports:
      - "9000:9000"
