version: "3.8"
services:
  backend:
    image: phongvanngo/medusajs-backend:latest
    container_name: medusa-server-default
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://novapo:novapo@127.0.0.1:3600/novapo-medusa
      REDIS_URL: redis://127.0.0.1:3700
      NODE_ENV: development
      JWT_SECRET: something
      COOKIE_SECRET: something
      PORT: 9000
    ports:
      - "9000:9000"

  postgres:
    image: postgres
    ports:
      - "3600:5432"
    environment:
      POSTGRES_USER: novapo
      POSTGRES_PASSWORD: novapo
      POSTGRES_DB: novapo-medusa

  redis:
    image: redis
    ports:
      - "3700:6379"

volumes:
  node_modules:
