version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - "$DOCKER_PORT:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - $VOLUME_DATA_PATH:/var/lib/postgresql/data