version: '3.9'
services:
  ghost:
    image: ghost:latest
    container_name: matkinh53-chemi-ghost-uat
    restart: always
    ports:
      - "$GHOST_DOCKER_PORT:2368"
    environment:
      url: $GHOST_URL
      database__client: mysql
      database__connection__host: $DB_HOST
      database__connection__port: $DB_PORT
      database__connection__user: $DB_USER
      database__connection__password: $DB_PASSWORD
      database__connection__database: $DB_DATABASE
      server__host: $SERVER_HOST
      server__port: $GHOST_DOCKER_PORT
    volumes:
      - $VOLUME_CONTENT_PATH:/var/lib/ghost/content